### ISSUE TITLE
Some help with configuration please

### ISSUE THREAD

**Issue by xbmcnut** [ben8p/lovelace-tab-redirect-card#1]
Thanks for making this! Exactly what I was after, a simple way to switch tabs when a temperature goes above a certain value.

Can you please explain a little more the configuration though? As it's a card, I'm assuming it remains hidden once configured correctly?

To test it, I'm using it on the first tab of a secondary Lovelace dashboard and have added the card to the first tab page. However, once configured, it's asking me to define the index. Where is that done? I've renamed by two tabs 0 and 1. Is that all I need to do?
```
You need to define redirect_to_tab_index (integer, starting from 0)

type: 'custom:tab-redirect-card'
redirect:
  - user: Pete
    entity_id:  light.family_room_lamp
    entity_state: 'on'
    redirect_to_tab: 1
```
I've also tried renaming the two tabs to redirect_to_tab_index_0 and redirect_to_tab_index_1 but that does not work either.

**Comment by ben8p** [comment]
Oh boy... My bad...

I made a mistake in the readme...

It should be 
```
type: 'custom:tab-redirect-card'
redirect:
  - user: Pete
    entity_id:  light.family_room_lamp
    entity_state: 'on'
    redirect_to_tab_index: 1
```
