### ISSUE TITLE
Feature Request: From/To states

### ISSUE THREAD

**Issue by xbmcnut** [ben8p/lovelace-tab-redirect-card#2]
Hi Ben,

Is it possible to add from: and to: to states as HA does? I have a Weber iGrill thermometer that I've created a custom giant gauge card for so my wife can see the temperature across the room. I want your integration to switch LL to the gauge tab but the sensor only has one state; either 'unknown' or not unknown so I'm using the following in my automations.
```
    trigger:
    - platform: state
      entity_id: sensor.igrill_thermometer
      from: 'unknown'

    trigger:
    - platform: state
      entity_id: sensor.igrill_thermometer
      to: 'unknown'
```
If it is not unknown, it reads the value but I can't put that either e.g > 20.
