### ISSUE TITLE
Username is case sensitive in card configuration 

### ISSUE THREAD

**Issue by stellarore** [ben8p/lovelace-tab-redirect-card#8]
Using the readme configuration example, if I have a user registered as “Foo” in home assistant, the redirect card won’t work. 

```
type: 'custom:tab-redirect-card'
redirect:
 - user: 'foo'
   entity_id: 'input.binary.is_home'
   entity_state: 'on'
   redirect_to_tab_index: 1
```
